### PR TITLE
Fixed focus on Audiomixer demo's popup

### LINKED ISSUE #205: Audio mixer: modals don't work with keyboard
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/audiomixer/

Tab to Save or New button and activate 

Expected:

One of the buttons to have focus in the modal and it to trap tab focus until dismissed. Esc should close the modal too (basically should work like our library's modal)

Actual:

Modal button doesn't have focus (not sure where focus is). Pressing tab focuses things behind the modal.

Possible fix:

Might be possible to switch to our regular modal (although it is styled differently).

### PR DESCRIPTION
**Pull request by sarvaje**
Fixed #205

### CODE REVIEW

**Comment by dstorey** [comment]
As this is JS I'll leave for @alrra to review.

File: audiomixer/scripts/ui.js [hunk 1]
```diff
@@ -1,7 +1,15 @@
 /* global $, audio, db */
-(function() {
+(function () {
 	'use strict';
 
+	var toArray = function (collection) {
+		var array = [];
```
Comment (molant) [inline audiomixer/scripts/ui.js]: Can you replace this with:
```javascript
return [].slice.call(collection);
```

so we are consistent with the rest of the projects?

**Review by molant — CHANGES_REQUESTED** [review]

File: audiomixer/scripts/ui.js (hunk 1 above)
Comment (sarvaje) [reply audiomixer/scripts/ui.js]: @molant done!

**Review by molant — APPROVED** [review]
